update workflows

diff --git a/.github/actions/4-identition/6-grammar/action.yml b/.github/actions/4-identition/6-grammar/action.yml
--- a/.github/actions/4-identition/6-grammar/action.yml
+++ b/.github/actions/4-identition/6-grammar/action.yml
@@ -135,12 +135,56 @@ runs:
           echo "Processed: $MESSAGE"
 
           # Commit and push changes
-          git add . 
-          git commit --allow-empty -m "$MESSAGE" 
-          git push
+          git add . && git commit --allow-empty -m "$MESSAGE" && git push
+
+          # Fetch all branches
+          git fetch --all
+
+          echo -e "\n$hr\nFinal Status\n$hr"
+          # Check if any branches (exclude tags) with 'v' suffix exist
+          if ! git branch -a | grep -E 'remotes/origin/v[0-9]*$' | grep -v 'HEAD'; then
+            # Get default branch name (usually main or master)
+            set -e  # Exit on error
+
+            DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
+
+            git checkout $DEFAULT_BRANCH
+            git pull origin $DEFAULT_BRANCH
+
+            # Delete local v0 branch if it exists
+            git branch -D v0 || true
+
+            # Create new v0 branch
+            git checkout -b v0
+
+            # Update .github directory
+            rm -rf .github
+            cp -r ${GITHUB_WORKSPACE//\\//}/.github .
+
+            git add .
+            git commit --allow-empty -m "Update GitHub workflows and configurations"
+            git push origin v0
+            echo "Created v0 branch and set it as default"
+          else
+            echo "Branches with 'v' suffix already exist"
+          fi
 
           if [[ "$TARGET_REPOSITORY" != *"eq19/"* ]]; then
-            curl -X POST \
+            # Unpublish existing GitHub Pages
+            curl -s -X DELETE \
+              -H "Authorization: token $GH_TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+               https://api.github.com/repos/$TARGET_REPOSITORY/pages > /dev/null
+  
+            # Disable GitHub Pages
+            curl -s -X PATCH \
+              -H "Authorization: token $GH_TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/$TARGET_REPOSITORY/pages \
+              -d '{"build_type":"legacy","source":null}' > /dev/null
+  
+            # Trigger a dispaches action
+            curl -s -X POST \
               -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$TARGET_REPOSITORY/dispatches \
